name       : kate
version    : 18.08.1
release    : 17
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.1/src/kate-18.08.1.tar.xz : 4afb79472935ed172e74a72e0008a0b9078523a07d831e16736638e7a4994dcb
license    :
    - GPL-3.0
    - LGPL-2.0
    - LGPL-3.0
component  : desktop.kde.core
optimize   : lto
summary    : KDE advanced text editor
description: |
    Kate is a multi-document, multi-view text editor by KDE. It features stuff like codefolding, syntaxhighlighting, dynamic word wrap, an embedded console, an extensive plugin interface and some prelimentary scripting support.
builddeps  :
    - pkgconfig(libgit2)
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5Script)
    - extra-cmake-modules
    - kconfig-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemmodels-devel
    - kjobwidgets-devel
    - knewstuff-devel
    - kparts-devel
    - ktexteditor-devel
    - kwallet-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - plasma-framework-devel
    - threadweaver-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
