name       : kate
version    : 19.12.3
release    : 38
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.3/src/kate-19.12.3.tar.xz : f60b52e5a6a78920ac703a458f1eaf0ced02ffcd8b5f2d49de9a48674eeb007c
homepage   : https://kde.org/applications/utilities/org.kde.kate
license    : GPL-3.0-or-later
component  : desktop.kde.core
optimize   : lto
summary    : KDE advanced text editor
description: |
    Kate is a multi-document, multi-view text editor by KDE. It features stuff like codefolding, syntaxhighlighting, dynamic word wrap, an embedded console, an extensive plugin interface and some prelimentary scripting support.
builddeps  :
    - pkgconfig(libgit2)
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5Script)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kitemmodels-devel
    - knewstuff-devel
    - ktexteditor-devel
    - kwallet-devel
    - plasma-framework-devel
    - threadweaver-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
