name       : kate
version    : 20.08.0
release    : 44
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.0/src/kate-20.08.0.tar.xz : aa0695f40cf9d491a08338f1c9b4331dfbb63cb311cf815ed0499b38940fa0db
homepage   : https://kde.org/applications/utilities/org.kde.kate
license    : GPL-3.0-or-later
component  : desktop.kde.core
optimize   : lto
summary    : KDE advanced text editor
description: |
    Kate is a multi-document, multi-view text editor by KDE. It features stuff like codefolding, syntaxhighlighting, dynamic word wrap, an embedded console, an extensive plugin interface and some prelimentary scripting support.
builddeps  :
    - pkgconfig(libgit2)
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5Script)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kitemmodels-devel
    - knewstuff-devel
    - ktexteditor-devel
    - kuserfeedback-devel
    - kwallet-devel
    - plasma-framework-devel
    - syntax-highlighting-devel
    - threadweaver-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache

    # remove docs
    rm -rf $installdir/usr/share/doc
