name       : kate
version    : 19.12.1
release    : 36
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.1/src/kate-19.12.1.tar.xz : 9d2401907e5b163d5af0af5b4d28383896ef709bcde7f6ee2234e1a3adc28a47
homepage   : https://kde.org/applications/utilities/org.kde.kate
license    : GPL-3.0-or-later
component  : desktop.kde.core
optimize   : lto
summary    : KDE advanced text editor
description: |
    Kate is a multi-document, multi-view text editor by KDE. It features stuff like codefolding, syntaxhighlighting, dynamic word wrap, an embedded console, an extensive plugin interface and some prelimentary scripting support.
builddeps  :
    - pkgconfig(libgit2)
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5Script)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kitemmodels-devel
    - knewstuff-devel
    - ktexteditor-devel
    - kwallet-devel
    - plasma-framework-devel
    - threadweaver-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
