name       : kate
version    : 17.04.2
release    : 2
source     :
    - https://download.kde.org/stable/applications/17.04.2/src/kate-17.04.2.tar.xz : 1045c5bee48ade8c229096eeaa8696eba4dac118bccc2a535f9ac553602fcaaf
license    :
    - GPL-3.0
    - LGPL-2.0
    - LGPL-3.0
component  : desktop.kde
summary    : KDE advanced text editor
description: |
    Kate is a multi-document, multi-view text editor by KDE. It features stuff like codefolding, syntaxhighlighting, dynamic word wrap, an embedded console, an extensive plugin interface and some prelimentary scripting support.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libgit2)
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5Script)
    - extra-cmake-modules
    - kconfig-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemmodels-devel
    - kjobwidgets-devel
    - knewstuff-devel
    - kparts-devel
    - ktexteditor-devel
    - kwallet-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - plasma-framework-devel
    - threadweaver-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
