name       : kate
version    : 18.12.1
release    : 21
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.1/src/kate-18.12.1.tar.xz : 67c21c729cfbf26f99250fc0a0a56ed7873a51bc61c2de6eb90662e7444e325d
license    : GPL-3.0-or-later
component  : desktop.kde.core
optimize   : lto
summary    : KDE advanced text editor
description: |
    Kate is a multi-document, multi-view text editor by KDE. It features stuff like codefolding, syntaxhighlighting, dynamic word wrap, an embedded console, an extensive plugin interface and some prelimentary scripting support.
builddeps  :
    - pkgconfig(libgit2)
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5Script)
    - extra-cmake-modules
    - kconfig-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemmodels-devel
    - kjobwidgets-devel
    - knewstuff-devel
    - kparts-devel
    - ktexteditor-devel
    - kwallet-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - plasma-framework-devel
    - threadweaver-devel
setup      : |
    %patch -p1 < $pkgfiles/Terminal-shortcut.patch
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
