name       : kate
version    : 20.12.0
release    : 49
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.0/src/kate-20.12.0.tar.xz : 69017d7369bbcac7a3e350fc0e02cbcfbf5ce09e89149e765a1cd647f3cb3c0f
homepage   : https://apps.kde.org/en/kate
license    :
    - GPL-2.0-or-later
    - GPL-3.0-only
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - LGPL-3.0-only
    - MIT
component  :
    - desktop.kde.core
    - ^kwrite : desktop.kde
optimize   : lto
summary    :
    - KDE advanced text editor
    - ^kwrite : KDE text editor
description:
    - Kate is a multi-document, multi-view text editor by KDE. It features stuff like codefolding, syntaxhighlighting, dynamic word wrap, an embedded console, an extensive plugin interface and some prelimentary scripting support.
    - ^kwrite : KWrite is a text editor by KDE, based on the Kates editor component.
patterns   :
    - ^kwrite :
        - /usr/share/metainfo/org.kde.kwrite.appdata.xml
        - /usr/bin/kwrite
        - /usr/share/applications/org.kde.kwrite.desktop
        - /usr/share/icons/hicolor/*/apps/kwrite.png
        - /usr/share/icons/hicolor/scalable/apps/kwrite.svgz
        - /usr/share/locale/*/LC_MESSAGES/kwrite.mo
builddeps  :
    - pkgconfig(libgit2)
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5Script)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kitemmodels-devel
    - knewstuff-devel
    - ktexteditor-devel
    - kuserfeedback-devel
    - kwallet-devel
    - plasma-framework-devel
    - syntax-highlighting-devel
    - threadweaver-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache

    # remove docs
    rm -rf $installdir/usr/share/doc
